config/routes.rb
FeedzirraTest::Application.routes.draw do
  resources :feedboxes

  get "viewfeed/refresh"

  get "viewfeed/add"

  get "viewfeed/all"

  get "viewfeed/one"

  match 'feedboxes/:id/refresh' => 'feedboxes#refresh', :as => :refresh_feedbox

  match 'feedboxes/:id/next' => 'feedboxes#next', :as => :next_story

  match 'feedboxes/:id/prev' => 'feedboxes#prev', :as => :prev_story

  root :to => 'feedboxes', :action => 'index'

end

app/models/feedbox.rb
class Feedbox < ActiveRecord::Base
  attr_accessible :last_update, :read_index, :title, :url

  has_many :stories

  def update_feed
    @feed = Feedzirra::Feed.fetch_and_parse(url)
    @feed.entries.each do |entry|
      stories.build(summary: entry.summary, title: entry.title, url: entry.url, published: entry.published, content: entry.content)
    end
    self.last_update = Time.now
    self.save
  end

  def current_story
    stories[read_index]
  end

  def next_article
    unless stories[read_index+1].nil?
      self.read_index+=1
      self.save
    end
  end

  def prev_article
    unless stories[read_index-1].nil? || read_index == 0
      self.read_index-=1
      self.save
    end
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :summary, :title, :url, :published, :content

  belongs_to :feedbox
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedboxes_controller.rb
class FeedboxesController < ApplicationController
  # GET /feedboxes
  # GET /feedboxes.json
  def index
    @feedboxes = Feedbox.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedboxes }
    end
  end

  # GET /feedboxes/1
  # GET /feedboxes/1.json
  def show
    @feedbox = Feedbox.find(params[:id])
    # @feedbox.update_feed
    @storyt = @feedbox.current_story.title
    @storyc = @feedbox.current_story.content.html_safe

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedbox }
    end
  end

  # GET /feedboxes/new
  # GET /feedboxes/new.json
  def new
    @feedbox = Feedbox.new
    #@feedbox.update_feed

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedbox }
    end
  end

  # GET /feedboxes/1/edit
  def edit
    @feedbox = Feedbox.find(params[:id])
  end

  # POST /feedboxes
  # POST /feedboxes.json
  def create
    @feedbox = Feedbox.new(params[:feedbox])
    @feedbox.update_feed

    respond_to do |format|
      if @feedbox.save
        format.html { redirect_to @feedbox, notice: 'Feedbox was successfully created.' }
        format.json { render json: @feedbox, status: :created, location: @feedbox }
      else
        format.html { render action: "new" }
        format.json { render json: @feedbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedboxes/1
  # PUT /feedboxes/1.json
  def update
    @feedbox = Feedbox.find(params[:id])

    respond_to do |format|
      if @feedbox.update_attributes(params[:feedbox])
        format.html { redirect_to @feedbox, notice: 'Feedbox was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedboxes/1
  # DELETE /feedboxes/1.json
  def destroy
    @feedbox = Feedbox.find(params[:id])
    @feedbox.destroy

    respond_to do |format|
      format.html { redirect_to feedboxes_url }
      format.json { head :no_content }
    end
  end

  def refresh
    @feedbox = Feedbox.find(params[:id])
    @feedbox.update_feed

    respond_to do |format|
      format.html { redirect_to @feedbox }
      format.json { head :no_content }
    end
  end

  def refresh_all
    Feedbox.all.each do |box|
      box.update_feed
    end

    respond_to do |format|
      format.html { redirect_to @feedbox  }
      format.json { head :no_content }
    end
  end

  def next
    @feedbox = Feedbox.find(params[:id])
    @feedbox.next_article
    # @feedbox.read_index+=1
    # @feedbox.save

    respond_to do |format|
      format.html { redirect_to @feedbox  }
      format.json { head :no_content }
    end
  end

  def prev
    @feedbox = Feedbox.find(params[:id])
    @feedbox.prev_article
    # @feedbox.read_index-=1
    # @feedbox.save

    respond_to do |format|
      format.html { redirect_to @feedbox  }
      format.json { head :no_content }
    end
  end
end

app/controllers/feedcaches_controller.rb
class FeedcachesController < ApplicationController
  # GET /feedcaches
  # GET /feedcaches.json
  def index
    @feedcaches = Feedcache.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedcaches }
    end
  end

  # GET /feedcaches/1
  # GET /feedcaches/1.json
  def show
    @feedcach = Feedcache.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedcach }
    end
  end

  # GET /feedcaches/new
  # GET /feedcaches/new.json
  def new
    @feedcach = Feedcache.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedcach }
    end
  end

  # GET /feedcaches/1/edit
  def edit
    @feedcach = Feedcache.find(params[:id])
  end

  # POST /feedcaches
  # POST /feedcaches.json
  def create
    @feedcach = Feedcache.new(params[:feedcach])

    respond_to do |format|
      if @feedcach.save
        format.html { redirect_to @feedcach, notice: 'Feedcache was successfully created.' }
        format.json { render json: @feedcach, status: :created, location: @feedcach }
      else
        format.html { render action: "new" }
        format.json { render json: @feedcach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedcaches/1
  # PUT /feedcaches/1.json
  def update
    @feedcach = Feedcache.find(params[:id])

    respond_to do |format|
      if @feedcach.update_attributes(params[:feedcach])
        format.html { redirect_to @feedcach, notice: 'Feedcache was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedcach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedcaches/1
  # DELETE /feedcaches/1.json
  def destroy
    @feedcach = Feedcache.find(params[:id])
    @feedcach.destroy

    respond_to do |format|
      format.html { redirect_to feedcaches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedboxes_helper.rb
module FeedboxesHelper
end

app/views/feedboxes/_form.html.erb
<%= form_for(@feedbox) do |f| %>
  <% if @feedbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedbox.errors.count, "error") %> prohibited this feedbox from being saved:</h2>

      <ul>
      <% @feedbox.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :last_update %><br />
    <%= f.datetime_select :last_update %>
  </div>
  <div class="field">
    <%= f.label :read_index %><br />
    <%= f.number_field :read_index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedboxes/edit.html.erb
<h1>Editing feedbox</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedbox %> |
<%= link_to 'Back', feedboxes_path %>

app/views/feedboxes/index.html.erb
<h1>Listing feedboxes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Last update</th>
    <th>Read index</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedboxes.each do |feedbox| %>
  <tr>
    <td><%= feedbox.title %></td>
    <td><%= feedbox.url %></td>
    <td><%= feedbox.last_update %></td>
    <td><%= feedbox.read_index %></td>
    <td><%= link_to 'Show', feedbox %></td>
    <td><%= link_to 'Edit', edit_feedbox_path(feedbox) %></td>
    <td><%= link_to 'Destroy', feedbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedbox', new_feedbox_path %>

app/views/feedboxes/new.html.erb
<h1>New feedbox</h1>

<%= render 'form' %>

<%= link_to 'Back', feedboxes_path %>

app/views/feedboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Feed Title:</b>
  <%= @feedbox.title %>
</p>

<p>
  <b>Url:</b>
  <%= @feedbox.url %>
</p>

<p>
  <b>Last update:</b>
  <%= @feedbox.last_update %>
</p>

<p>
  <b>Read index:</b>
  <%= @feedbox.read_index %>
</p>

<p>
  <b>Story Title</b>
  <%= @storyt %>
</p>

<p>
  <%= @storyc %>
</p>


<%= link_to 'Prev', prev_story_path(@feedbox) %>
<%= link_to 'Next', next_story_path(@feedbox) %>
<p></p>
<%= link_to 'Edit', edit_feedbox_path(@feedbox) %> |
<%= link_to 'Back', feedboxes_path %> |
<%= link_to 'Refresh', refresh_feedbox_path(@feedbox) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedzirraTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>